export const MOST_LIKELY_TO_PROMPTS: string[] = [
  "Try to convince a friend to do drugs with them",
  "Get banned from a cruise ship",
  "Accidentally send a spicy text to their boss",
  "Start a cult and actually get followers",
  "Get arrested at a children's birthday party",
  "Fake their own death for attention",
  "Get into a fistfight at a wedding",
  "Become a Florida Man headline",
  "Drunk-text their ex at 3am... on a Tuesday",
  "Get catfished and still go on the date",
  "Show up to work still drunk from the night before",
  "Get kicked out of an all-you-can-eat buffet",
  "Accidentally join a gang",
  "Start an OnlyFans and tell no one",
  "Cry during a job interview",
  "Get lost in their own neighbourhood",
  "Survive a zombie apocalypse by pure luck",
  "Get a face tattoo on impulse",
  "Be the reason a friend group falls apart",
  "Eat something off the floor at a restaurant",
  "Try to fight a bouncer and lose badly",
  "Get scammed by an obvious pyramid scheme",
  "Fall asleep during their own birthday party",
  "Accidentally burn down a kitchen trying to boil water",
  "Get banned from a country",
  "Marry someone they met that same week",
  "Bring a weapon to a pillow fight",
  "Get caught talking to themselves in public",
  "Ghost someone and then ask why they stopped texting",
  "Start a bar fight over something incredibly petty",
  "Lie on their CV and somehow get the job",
  "Skinny dip in a public fountain",
  "Get way too competitive at a kids' board game",
  "Have a full emotional breakdown in an Uber",
  "Accidentally commit a crime without realising",
  "Flirt with a cop to get out of a ticket",
  "Start a conspiracy theory that people actually believe",
  "Get stuck in a baby swing at a playground",
  "Peak in high school and never shut up about it",
  "Survive purely on energy drinks and audacity",
  "Walk into a glass door in front of a crowd",
  "Get cancelled on social media",
  "Be the person who clogs the toilet at a party",
  "Accidentally propose to someone",
  "Start a fight in a McDonald's at 2am",
  "Sell everything they own to fund a terrible business idea",
  "Get bitten by an animal they were trying to pet",
  "Sleep through a natural disaster",
  "Have a wardrobe malfunction at the worst possible moment",
  "Get way too emotionally attached to a reality TV show",
  "Be the one friend who always takes the joke too far",
  "Get permanently banned from a fast food chain",
  "Move to another country on a whim with no plan",
  "Pass out at a party and become a meme",
  "Say 'I love you' on a first date",
  "Get lost in IKEA for over 2 hours",
  "Start an argument with a stranger over something that doesn't matter",
  "Get caught stealing hotel toiletries in bulk",
  "Be the person who ruins the group photo",
  "Win a Darwin Award",
];
